"use client";

import { useState } from "react";

export function ExportBundle({ projectId, projectName }: { projectId: string; projectName: string }) {
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  async function downloadCsv() {
    setBusy(true);
    setErr(null);
    try {
      const dictRaw = sessionStorage.getItem(`scores:dict:${projectId}`);
      const llmRaw = sessionStorage.getItem(`scores:llm:${projectId}`);
      const rows: Array<Record<string, unknown>> = [];
      const dict = new Map(
        dictRaw ? (JSON.parse(dictRaw) as Array<{ id: string; score: number }>).map((r) => [r.id, r.score]) : [],
      );
      const llm = new Map(
        llmRaw
          ? (JSON.parse(llmRaw) as Array<{ id: string; score: number | null; rationale?: string }>).map((r) => [r.id, r])
          : [],
      );
      const ids = new Set([...dict.keys(), ...llm.keys()]);
      for (const id of ids) {
        const l = llm.get(id);
        rows.push({
          id,
          dict_score: dict.get(id) ?? "",
          llm_score: l?.score ?? "",
          llm_rationale: (l?.rationale ?? "").replaceAll("\n", " "),
        });
      }
      const header = Object.keys(rows[0] ?? { id: "", dict_score: "", llm_score: "", llm_rationale: "" });
      const csv = [header.join(",")]
        .concat(rows.map((r) => header.map((h) => JSON.stringify(r[h] ?? "")).join(",")))
        .join("\n");
      downloadBlob(`${slug(projectName)}-scores.csv`, csv, "text/csv");

      let reflexivity = "";
      try {
        const res = await fetch(`/api/projects/${projectId}/reflexivity`);
        if (res.ok) {
          const body = (await res.json()) as { notes: Array<{ body: string; createdAt: string; linkedRunId: string | null }> };
          reflexivity = body.notes
            .map((n) => `- **${new Date(n.createdAt).toISOString()}**${n.linkedRunId ? ` (run ${n.linkedRunId})` : ""}\n  ${n.body.replace(/\n/g, "\n  ")}`)
            .join("\n");
        }
      } catch {
        // reflexivity is optional for export
      }

      const featuresRaw = sessionStorage.getItem(`features:${projectId}`);
      const features: Array<{ name: string; kind: string; pattern: string; signal: string }> = featuresRaw
        ? JSON.parse(featuresRaw)
        : [];

      const appendix = renderMethodsAppendix({ projectId, projectName, n: rows.length, reflexivity, features });
      downloadBlob(`${slug(projectName)}-methods-appendix.md`, appendix, "text/markdown");
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="mt-6 space-y-3">
      <button
        onClick={downloadCsv}
        disabled={busy}
        className="rounded bg-primary px-4 py-2 text-primary-foreground disabled:opacity-60"
      >
        {busy ? "Preparing…" : "Download scores + methods appendix"}
      </button>
      {err ? <p className="text-sm text-destructive">{err}</p> : null}
    </div>
  );
}

function renderMethodsAppendix({
  projectId,
  projectName,
  n,
  reflexivity,
  features,
}: {
  projectId: string;
  projectName: string;
  n: number;
  reflexivity: string;
  features: Array<{ name: string; kind: string; pattern: string; signal: string }>;
}): string {
  const featureSection = features.length
    ? ["## Promoted macro features", "", ...features.map((f) => `- \`${f.name}\` (${f.kind}) — pattern \`${f.pattern}\`; signal: ${f.signal}`), ""].join("\n")
    : "";
  const reflexivitySection = reflexivity
    ? ["## Reflexivity log", "", reflexivity, ""].join("\n")
    : "";
  return [
    `# Methods appendix — ${projectName}`,
    "",
    `_Generated by the LLM Inference Tool on ${new Date().toISOString()}._`,
    "",
    `**Project ID:** ${projectId}`,
    `**Documents scored:** ${n}`,
    "",
    "## Procedure",
    "",
    "1. Constructs and scale anchors were pre-registered before any LLM scoring.",
    "2. A traditional dictionary measure (Loughran–McDonald) was computed first; the dictionary list and version are embedded in the run's reproducibility manifest.",
    "3. LLM construct scoring was performed using the provider and model recorded in the manifest with a two-stage protocol: a small randomly-sampled subsample was reviewed by the researcher before the full-corpus pass was initiated.",
    "4. Deviation analysis (Pearson and Spearman correlation, top-disagreement inspection) was performed to triangulate the LLM measure against the traditional measure.",
    "5. (Optional) Macro-inference was used to inductively surface candidate signals, which were operationalized as keyword or presence features and added to the combined regression spec.",
    "6. (Optional) Primary / LLM-only / combined regression specifications were fit in-tool via the pinned Python sidecar.",
    "",
    featureSection,
    reflexivitySection,
    "## Disclosures",
    "",
    "- **LLM-assisted measurement.** The construct score was produced by a large language model against the construct definition and scale anchors supplied above. LLM outputs are probabilistic; inter-run and inter-model agreement should be reported in any publication.",
    "- **Known limitations.** LLM scoring can be sensitive to prompt wording, negation, and directional framing. The combined-regression specification and the top-disagreement inspection in this tool are provided as partial mitigations.",
    "- **Reproducibility.** The manifest records the exact model version string returned by the provider, prompt version, temperature, and seed (where supported by the provider). Data uploaded to this tool is not persisted server-side.",
  ].join("\n");
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function downloadBlob(filename: string, body: string, type: string) {
  const blob = new Blob([body], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
